 version: 2
 jobs:
   build:
     working_directory: ~/react_ci
     docker:
       - image: circleci/node:7.10
     steps:
       - checkout
       - run: echo "echo pwd"
       - run: pwd
       - run: echo "echo ls -l"
       - run: ls -l react_ci

       - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

       - run:
          name: Install npm wee
          command: npm install

   test:
     docker:
       - image: circleci/node:7.10
     steps:
       - checkout
       - run:
          name: Test
          command: npm test
 workflows:
   version: 2
   build_and_test:
     jobs:
       - build
       - test:
          requires:
            - build
